### ISSUE TITLE
Obrigado à todos

### ISSUE THREAD

**Issue by vitorbritto** [frontendbr/sugestoes#1]
Quero agradecer à todos os envolvidos por esta grande iniciativa e que depois de muito tempo, sinto a vontade de tecer comentários que mais parecem livros para poder compartilhar conhecimento com vocês. 

Vamos continuar nesta pegada, mantendo o ciclo do conhecimento em constante movimento. =]

**Comment by LFeh** [comment]
Está muito foda! E vamos que vamos

**Comment by eduardojmatos** [comment]
@vitorbritto digo o mesmo! Tá legal demais tudo o que tá rolando :satisfied:
