### ISSUE TITLE
Newsletter Front-End Brasil

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/sugestoes#10]
Newsletter com indicações de links com dicas de Front-End e talvez os tópicos quentes que estão bombando aqui no fórum.

**Comment by Mendrone** [comment]
Tenho pensado a algum tempo em fazer isso. 

O que acham, @vitorbritto @fdaciuk @eduardojmatos @willianjusten @LFeh @diogomoretti ?

**Comment by LFeh** [comment]
Vocês acham que a galera ainda usa? Eu mesmo usava bastante, hoje não mais.

**Comment by diogomoretti** [comment]
Eu até uso, mas vejo que já temos bastante, mesmo em PT-BR. Até porque será mais um projeto para manter e correrá o risco de morrer ou ficar semanas sem enviar.

**Comment by fdaciuk** [comment]
Talvez poderíamos colocar as discussões mais interessantes na BrazilJS Weekly.. lá tem uma galera que assina, poderia alcançar mais gente que ainda não conhece o fórum =)

**Comment by theandersonn** [comment]
Colocar na BrazilJS Weekly é super legal.

**Comment by eduardojmatos** [comment]
+1 pra colocar na BrazilJS Weekly!

O problema de fazer um nosso é mais uma newsletter pra consumir. Eu, por exemplo, já estou com duas weekly atrasadas (da JavaScript e NodeJS).

**Comment by LFeh** [comment]
Também prefiro aproveitar a BrazilJS Weekly, que inclusive, é bem consolidada.

Como poderíamos nos organizar para fazer isso?

**Comment by diogomoretti** [comment]
O que vocês querem dizer com "colocar na BrazilJS"?

**Comment by eduardojmatos** [comment]
@diogomoretti dá pra sugerir links lá, daí poderíamos enviar esporadicamente as melhores issues, ou mais comentadas. Mas concordo com você no sentido de que, se não tiver ninguém mantendo isso, será mais um repo que corre risco de ficar inativo

**Comment by LFeh** [comment]
Enviar esporadicamente links e discussões é a melhor alternativa.

**Comment by fdaciuk** [comment]
Isso! A ideia era sugerir algumas discussões na issue da BrazilJS Weekly =)

**Comment by LFeh** [comment]
Algum avanço pessoal?

**Comment by niltoncsr** [comment]
Opa, cheguei agora aqui na discussão mas vou dar o meu pitaco :)

Acho que pode ser criada uma seção na BrazilJS Weekly não só com as hot issues, mas também de posts de autores daqui! A gente poderia submeter semanalmente os links, e os caras mandavam junto na newsletter. Acredito que seria até um ótimo incentivo pra gente escrever e divulgar o nosso trabalho.

Quem acha que vinga? Bora tocar pra frente?! :smiley:

**Comment by kvnol** [comment]
Já que existe a Weekly da BrazilJS, seria a melhor opção mesmo. Mas no caso da criação de uma newsletter do FrontendBR, usar o https://mjml.io/ é uma puta ferramenta boa para construção das news.

**Comment by niltoncsr** [comment]
O que for a melhor alternativa! Caso não role na da BrazilJS, a gente pode usar essa ferramenta, @kvnol, pra criar os templates, e o sistema da newsletter nós mesmos poderíamos desenvolver :wink:

**Comment by joaodfmota** [comment]
Acredito que esta sugestão seria bacana, eu por exemplo consigo me localizar e priorizar em leituras de conteúdo através do e-mail. Enfim se precisarem eu tenho algum conhecimento em inbound marketing o qual acredito que facilitaria no uso desse tipo de contato.

Sinceramente acredito que isso poderia muito dar um up no relacionamento entre nosso setor, mas tem um porém, ferramentas legais deste tipo geram custo, e não tenho a mínima ideia de como funciona o orçamento/gerenciamento dos nobres colegas que mantem este projeto.

**Comment by ricardogouveia3** [comment]
Alguém usa o feedly?
Acho melhor pra organizar o que tenho que ler.
E, colocando na Weekly do BrazilJS, ficamos restritos a falar de JS?

**Comment by LFeh** [comment]
Não foi pra frente, vou fechar por enquanto.
