### ISSUE TITLE
Integração do Vagas com Slack

### ISSUE THREAD

**Issue by herberthenrique** [frontendbr/sugestoes#11]
Eu estava pensando, assim como existe uma integração do channel de vagas com o twitter poderia existir uma com o slack do frontendbr.
Alguém pode acabar usando mais o slack, ou dando mais atenção pra ele :)

**Comment by LFeh** [comment]
@frontendbr/admins

**Comment by matmarsiglio** [comment]
Vejo como pró algo que facilite a visualização de coisas através de um canal, mas como contra quando se é hard user de Slack, tu tens uns 5 a 10 grupos e isso talvez só sujaria as notificações de Slack, o que não seria um grande ganho. 

Alguém vê diferente? Posso estar viajando, mas eu e uns aí que conheço desligaríamos notificações desse canal e continuariamos usando o GitHub apenas.

**Comment by diogomoretti** [comment]
Concordo com o @matmarsiglio. Pessoal já tem o GH e o Twitter. Também temos que tomar cuidado para o famoso "abraçar o mundo" e depois ter milhares de meios para dar manutenção.

**Comment by LFeh** [comment]
Concordo com vocês. Também tenho certa resistência ao Slack pelo fato de ser uma plataforma fechada. Escala menos ainda que o Twitter.

**Comment by Mendrone** [comment]
Concordo com os senhores, já temos canais de comunicação suficientes sobre as vagas.

**Comment by eduardojmatos** [comment]
@herberthenrique cara, faz um pouco de sentido seu ponto. Mas tendo a concordar com os itens levantados pelo @matmarsiglio @diogomoretti. 

De qualquer modo, ter essas vagas postadas lá no channel de #vagas não iria atrapalhar em nada - e concordo com você que até ajudaria quem não entra sempre no repo de vagas e não segue o Twitter do vagas, mas está sempre presente no Slack do Frontend Brasil. Não vejo o porquê de isso ser ruim não =D

**Comment by LFeh** [comment]
@eduardojmatos Se não for o problema manter o suporte e tudo mais, e conseguir fazer, pode mandar ver \o
