### ISSUE TITLE
Destaques do fórum

### ISSUE THREAD

**Issue by psicotropicos** [frontendbr/sugestoes#13]
O que vocês acham de criar uma página na Wiki do fórum para reunir as melhores threads discutidas nele, melhores respostas ou issues com maior relevância?

**Comment by LFeh** [comment]
Acho do carario.

@frontendbr/admins

**Comment by Mendrone** [comment]
Manda ver, mano! Acho animal!

**Comment by fdaciuk** [comment]
Ótima ideia! :dancer: :dancer: :sparkles:

**Comment by LFeh** [comment]
@psicotropicos Você consegue tocar isso?

**Comment by psicotropicos** [comment]
@LFeh Consigo sim, claro! 🤘

**Comment by eduardojmatos** [comment]
@psicotropicos @LFeh acho bem bom!!! Depois podemos tweetar isso esporadicamente hein :)

**Comment by psicotropicos** [comment]
@LFeh Para que conseguir gerenciar a Wiki eu tenho que estar na organização :p

**Comment by LFeh** [comment]
Vou botar!

**Comment by diogomoretti** [comment]
Chegando atrasado, mas vamos lá...

Penso que não é necessário... Sei que a intenção é das melhores, mas seria mais uma coisa para ficar atualizando. Vou levantar alguns pontos:

- Mais um "filho para criar" e correr o risco (alto) de ficar legado;
- Qual seria o critério para eleger os "melhores posts"? Isso é bem subjetivo;
- Penso que a primeira leva poderia até sair, mas não iriamos atualizar mais;
- Se realmente quisermos fazer, poderíamos "setar" uma label para isso e não duplicar conteúdo.

Enfim, não acho necessário... mas caso queiramos, a última opção da lista acho mais viável  :stuck_out_tongue_winking_eye:

**Comment by psicotropicos** [comment]
Pontos interessantes @diogomoretti, eu não tinha olhado por esse prisma quando fiz a sugestão.

Meu pensamento inicial era deixar mais fácil de encontrar respostas que fossem mais relevantes para os problemas, principalmente em threads e dúvidas técnicas.

Outra coisa seria encontrar dúvidas duplicadas, afinal, nós sabemos que ainda tem muita gente que não procura.

Mas fica aberta a discussão, se vocês acharem que é válida a idéia eu toco o barco, caso contrário, apoio a ideia das labels

✌️
