### ISSUE TITLE
Repositório de blogs

### ISSUE THREAD

**Issue by niltoncsr** [frontendbr/sugestoes#15]
Olá a todos!
Gosto de acompanhar blogs técnicos, sempre me acrescentam conhecimento sobre um assunto que ainda não havia trabalhado, ou me salva na resolução de um problema que não encontrava solução. Inspirado por isso e por amigos resolvi começar a escrever também, porém é um trabalheira fazer seu conteúdo aparecer quando se está começando.
Tomando [bons exemplos](https://github.com/dunderlabs/python_blogs) como base, acho interessante criarmos um repo com uma lista dos blogs produzidos pela comunidade brasileira, alimentada pelos próprios autores, separados por categoria ou conteúdo mais abordado. Isso ajuda a listar quais blogs temos, fica mais fácil de mostrar novos, de consolidar os mais antigos, e até inspirar quem quer começar ou parou e quer voltar. Win-win.

E aí, o que acham?! ;D

**Comment by LFeh** [comment]
Oh soh

https://github.com/LFeh/frontend-feed
