### ISSUE TITLE
Sugestão de label para as vagas

### ISSUE THREAD

**Issue by rafaelassumpcao** [frontendbr/sugestoes#16]
galera estava percebendo aqui uma grande procura por jobs que sejam full remote e as labels das issues de vagas do frontendbr apenas indicam remoto. o que as vezes frusta quem busca uma vaga full por exemplo tem vagas que tem a label remoto mas é de apenas um dia por semana por exemplo.

Poderia haver uma distinção de labels remoto tipo sei lá algo como

    Remoto Parcial
    Remoto Integral

se gostarem da sugestão e tiver uma nomenclatura melhor, por favor joga na roda!

**Comment by LFeh** [comment]
@frontendbr/admins

**Comment by fdaciuk** [comment]
Acho válido :+1:

**Comment by mtmr0x** [comment]
👍

**Comment by eduardojmatos** [comment]
👍

**Comment by LFeh** [comment]
Então vamos nessa :)
