### ISSUE TITLE
Bot para o Twitter @frontendbrvagas

### ISSUE THREAD

**Issue by omarkdev** [frontendbr/sugestoes#17]
Não sei as postagens no Twitter frontendbrvagas são feitas de forma automática e manual, acredito que seja manual, se for automática, desconsidere minha issue.

Poderiamos montar uma aplicação junto com o IFTTT quando é aberto uma nova issue, disparamos um novo tweet.

**Comment by eduardojmatos** [comment]
@omarkdev são automáticas. Tem um serviço checando as issues e postando no Twitter.

O @fdaciuk pode explicar melhor como funciona ;)

**Comment by fdaciuk** [comment]
Fala @omarkdev! Não lembro exatamente o motivo, mas tivemos alguns problemas ao usar o IFTTT.. ae fiz [esse _service_](https://github.com/fdaciuk/github2twitter/), que posta automaticamente, usando webhooks do GitHub =)

O projeto está hospedado no `now` =)
