### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by filippobarcellos** [frontendbr/sugestoes#18]
Fala pessoal!

Devido muitas vezes a dificuldade de um desenvolvedor iniciante construir/participar de projetos reais o que acham da ideia abaixo?

Baseado no http://www.dailyui.co/, que tem a proposta de praticar design diariamente, se não me engano por 100 dias. O que acham de fazermos o mesmo com o nosso mundo front-end?

Poderia ser algo escalável, começando com algo básico e ir crescendo..

Não sei se já tem algo parecido. Caso tenha, peço desculpas.

Abraço!

**Comment by kvnol** [comment]
@filippobarcellos eu acho uma ideia do caralho, até estou montando algo similar com o [Devnspiration](https://github.com/devnspiration) (que, devido ao tempo, está meio parado e que seria massa ter a ajuda da comunidade).

A ideia do Devsnpiration seria inspirar desenvolvedores, mas depois percebi que já temos algo parecido com o [CollectUI](collectui.com), mas acho que não haveria problema de mudar um pouco o mote do Devnspiration para algo como é o Daily UI.

**Comment by ricardogouveia3** [comment]
Tem o [Javascript30](https://javascript30.com/) do Wes Bos, é muito bom porque ele pega não do inicio do ensino de JS, mas a partir do momento em que você acabou algum curso ou tutorial gratuito e está sem ter o que fazer (tipo sem idéia de projeto).

Não sei se front-end cairia bem por ser bem amplo, mas um desses de CSS eu com certeza participaria.

**Comment by LFeh** [comment]
Nossa, só vi agora.

Penso que não cabe nessa organização.

Sugiro criar um draft disso dentro de https://github.com/frontendbr/open-source e tentar juntar uma galera para tocar.

**Comment by kvnol** [comment]
@LFeh, será tem como mover essa issue pra lá?

**Comment by LFeh** [comment]
Consigo

**Comment by LFeh** [comment]
This issue was moved to frontendbr/open-source#42
