### ISSUE TITLE
[ Ferramenta ] Integração do forum com o Telegram

### ISSUE THREAD

**Issue by LFeh** [frontendbr/sugestoes#19]
_From @suissa on June 13, 2017 0:3_

Galera eu inicie um forum para os alunos da Webschool e estamos usando o mesmo esquema daqui, utilizando as ISSUES, porém criei um grupo no Telegram [https://t.me/forumwebschool](https://t.me/forumwebschool) onde integrei com um BOT do Github que fica escutando nosso repositório [https://github.com/Webschool-io/forum](https://github.com/Webschool-io/forum) e toda movimentação do repo ele nos avisa e podemos responder uma ISSUE diretamente como uma resposta à uma mensagem no chat do Telegram.

![screen shot 2017-06-12 at 8 52 29 pm](https://user-images.githubusercontent.com/75607/27060296-29443842-4fb2-11e7-810d-989fe3e87bcf.png)

Caso alguém queira testar isso criei um grupo de teste https://t.me/joinchat/AAAAAEQgwS5nIXaoS_6R9A porém algum dos admins precisa entrar e configurar o bot, alguém se habilita??

cc @diogomoretti @fdaciuk @eduardojmatos @LFeh @Mendrone @mtmr0x

_Copied from original issue: frontendbr/forum#595_

**Comment by LFeh** [comment]
_From @fdaciuk on June 13, 2017 14:43_

Da hora hein @suissa! :D
Pra galera que usa bastante Telegram, acho que faz bastante sentido =)

**Comment by LFeh** [comment]
Não uso o Telegram, alguém pode testar? @frontendbr/admins

**Comment by LFeh** [comment]
_From @eduardojmatos on June 13, 2017 19:26_

@suissa bacana mano. Depois a gente pode mover essa issue pro https://github.com/frontendbr/sugestoes/ ? Só pra ficar centralizada lá as novas ideias.

Eu uso, vou testar aqui então!

**Comment by LFeh** [comment]
_From @nandomoreirame on June 13, 2017 21:8_

@woliveiras da pra usar no Telegram do @training-center :)

**Comment by woliveiras** [comment]
Verdade @LFeh

**Comment by mmalaquias1** [comment]
Cara muito boa essa ideia!

**Comment by suissa** [comment]
@LFeh Telegram eh o melhoooorrrr!
