### ISSUE TITLE
Lugar para disponibilizar links

### ISSUE THREAD

**Issue by willianjusten** [frontendbr/sugestoes#2]
Fala galera, assim como o @vitorbritto, eu gostaria de agradecer por finalmente estar vendo discussões legais e completas por uma galera que não via fazia tempo.

Minha sugestão aqui, é que tenhamos alguma forma de disponibilizar diversos links que vemos no dia a dia. Eu vejo muito conteúdo o dia inteiro e acho que seria legal compartilhar com todos.

@frontendbr/admins o que vocês acham disso?

Se acham legal, como fazer?

**Comment by nicholasess** [comment]
@willianjusten vocês poderiam fazer isso, utilizando o http://br.welearnit.co :+1:

**Comment by willianjusten** [comment]
@nicholasess, cara, eu acho que isso já foi discutido com alguns dos outros admins e decidimos que a ideia ficará aqui no github para o github. Pois já é uma plataforma que todos estão acostumados a usar e que não precisa de nenhum cadastro a mais ou etc...

**Comment by mvfsilva** [comment]
@willianjusten cria um repositório e organiza por assunto, no estilo da awesome svg

**Comment by Mendrone** [comment]
@willianjusten eu curto a ideia, tem muita coisa boa sendo divulgada por ai, só precisaríamos ficar atentos pra manter a qualidade e evitar muito conteúdo repetido. 

:+1:

**Comment by willianjusten** [comment]
@Mendrone, é exatamente isso que me preocupa, a repetição e  qualidade... O que o @mvfsilva falou é uma boa, pois para cada adição, seria necessário um PR, o que acabaria fazendo com que tivesse uma moderação mais em cima...

Mas também não sei se a galera iria querer isso, por ser mais "demorado"...

**Comment by eduardojmatos** [comment]
@willianjusten um repo seria bacana sim. O problema é a burocracia de abrir PR e etc... Mas podemos tentar, pra ver se rola :smile:

**Comment by nicholasess** [comment]
O mais foda disso tudo, é que vocês vão ter muita dificuldade para fazer essa organização, mas pensei na possibilidade de vocês atrelarem um gist com a lista referente aquela issue.

**Comment by willianjusten** [comment]
@frontendbr/admins, se alguém tiver uma boa ideia. Eu confesso que acho legal ter isso, mas não consigo pensar em nada para facilitar ahuahau

@nicholasess , num entendi. Como assim gist?

**Comment by nicholasess** [comment]
Por exemplo

Na issue 123, temos diversos links bacanas que envolvem a discussão, pra não perder o sentido daqueles links com a conversa.
Vocês admins, alocam um gist com os links daquela conversa, criam um padrão:"Forum frontend issue 123".

**Comment by vitorbritto** [comment]
Para disponibilizar links, eu ainda acredito que o [Cerebro](https://github.com/cerebrobr) seja um ambiente bom para isso. 

Sobre repetições de tópicos, em qualquer ambiente de discussão/debate haverão tópicos repetidos. Acho inevitável haver repetições. A questão é quando alguém notar ou detectar tal repetição, deve mencionar o autor, referenciar para a _issue_ já existente e fechar a repetida.

@frontendbr/admins

**Comment by fdaciuk** [comment]
> Para disponibilizar links, eu ainda acredito que o Cerebro seja um ambiente bom para isso.

+1 para deixar no Cérebro. Assim já movimenta os repos por lá xD

**Comment by willianjusten** [comment]
Show =)

**Comment by LFeh** [comment]
+1 para manter no Cérebro \o

**Comment by rkb81** [comment]
Falando em links os links dos principais canais deste grupo poderiam estar no readme facilitando o acesso, como por exemplo o slack do frontend brasil.

Colocar estes no Cérebro seria legal também.

**Comment by fdaciuk** [comment]
Boa @rkb81 +1

**Comment by willianjusten** [comment]
Boa sugestão @rkb81

**Comment by LFeh** [comment]
Perfeito.

Vocês colocam no Cérebro?

**Comment by Mendrone** [comment]
Boa @rkb81 

+1 para colocar no Cérebro também.

**Comment by LFeh** [comment]
Alias, podemos tentar fazer um cross maior entre a org do Cerebro e a nossa org, não? Até porque tem muitas pessoas envolvidas nas duas.

@frontendbr/admins

**Comment by fdaciuk** [comment]
@LFeh :dancer: :dancer:

**Comment by eduardojmatos** [comment]
@frontendbr/admins estou de acordo :+1:

**Comment by willianjusten** [comment]
Total de acordo.
