### ISSUE TITLE
Nova página para o Front-end Brasil

### ISSUE THREAD

**Issue by kvnol** [frontendbr/sugestoes#21]
Continuando a ideia da nova identidade do Front-end Brasil (#20), seria interessante haver uma reformulação na página http://frontendbr.com.br/. Pensei em algo dessa forma:

![image](https://user-images.githubusercontent.com/3299130/27775856-482b42da-5f7c-11e7-908f-09869837f819.png)

**Comment by kvnol** [comment]
c/c @LFeh @mtmr0x @Mendrone @diogomoretti @fdaciuk @eduardojmatos @willianjusten @theandersonn :heart:

**Comment by theandersonn** [comment]
@kvnol Gostei! Fechando uma nova identidade e paleta de cores. 
Achei essa estrutura melhor que a atual.

**Comment by diogorodrigues** [comment]
Hey @kvnol . Também penso ser interessante a interface do site ganhar um update. Sua ideia de algo mais minimalista é uma boa, mas repensaria alguns pontos importantes:

- É interessante manter o conteúdo principal above the fold. Portanto, o texto 'Sobre' poderia ceder lugar à alguma frase de impacto, concisa e direta, seguida dos botões.

- Sei que você se baseou no layout atual, fazendo uma releitura da interface. No entanto, sinto falta de um 'preenchimento' a mais da tela, apesar do estilo minimalista.

Parabéns pela iniciativa. Continue postando mais opções. =D
Se ajudar (e se achar interessante seguir essa linha), criei uma página para o projeto que difere da página principal. Veja: https://frontendbr.com.br/eventos/

**Comment by kvnol** [comment]
@diogorodrigues Concordo totalmente com seus pontos. Como eu tive essa ideia do nada, ao entrar no site do frontendbr, não montei conteúdo. Só adaptei no novo layout.

Mas acho massa ter um conteúdo melhor (mais impactante), vou montar outras coisas e fico no aguardo de mais sugestões e telas de outras pessoas.

E ah, a página de eventos ficou linda! ♥

**Comment by LFeh** [comment]
Mano, eu nem sabia que tinhamos um site. Juro, hahaha

**Comment by fdaciuk** [comment]
@LFeh como não cara? Tu até sugeriu uma reformulação dele haha https://github.com/frontendbr/frontendbr.github.io/issues/1

**Comment by LFeh** [comment]
Nossa, verdade, esqueci completamente, hahahuheau

**Comment by kvnol** [comment]
Com base na nova versão de identidade que [mandei na outra issue](https://github.com/frontendbr/sugestoes/issues/20#issuecomment-314502662), estava repensando o layout e a aplicação da mesma ficaria (está ficando) assim:

![image](https://user-images.githubusercontent.com/3299130/28151427-e53be236-6770-11e7-9a21-a9cfbead18b6.png)

**Comment by ricardogouveia3** [comment]
Usei a minha [sugestão de logo](https://github.com/frontendbr/sugestoes/issues/20) pra fazer um layout, já usando as fotos do FrontInSampa 2017.

Ainda vou trabalhar na consistência, e fazer um pra celular.

Feedbacks? <3

![desktop hd copy](https://user-images.githubusercontent.com/8239868/28242945-84afbdd0-6990-11e7-956d-3592a3dc7505.png)

**Comment by kvnol** [comment]
Conforme conversado com o @mtmr0x e @Mendrone, vamos segurar essa issue até a decisão final da nova identidade do FrontendBR, construção do style guide e tal.

Até lá, issue. :heart:

**Comment by kvnol** [comment]
Com o sucesso da issue #20 (e votação na #24), acho que podemos voltar a conversar sobre isso.

A brand foi publicada no repositório: https://github.com/frontendbr/brand com paleta de cores, etc. Já podemos seguir essas cores.

**Comment by kvnol** [comment]
Voltamos a falar sobre isso [na issue do site](https://github.com/frontendbr/frontendbr.github.io/issues/1), mas para que vocês vejam como está ficando:

desk - figma.com/proto/Q9FrYXlQKZar06pgRm9mSY0i/Front-end-Brasil?node-id=27%3A0&scaling=min-zoom
tablet - figma.com/proto/Q9FrYXlQKZar06pgRm9mSY0i/Front-end-Brasil?node-id=50%3A15&scaling=min-zoom
mobile - figma.com/proto/Q9FrYXlQKZar06pgRm9mSY0i/Front-end-Brasil?node-id=50%3A773&scaling=min-zoom
