### ISSUE TITLE
Membros

### ISSUE THREAD

**Issue by joaodfmota** [frontendbr/sugestoes#22]
Uma área onde nos cadastraremos conforme nossa área de atuação por segmento de trabalho e/ou tecnologias utilizadas.

Acredito que facilitaria na troca de experiências entre segmentos, por exemplo:

João atua como frontend em uma agência de marketing ditial focada no inbound e blablabla

Assim alguém que trabalha ou está iniciando necessite de alguma ajuda possa me contatar e descobrir como trabalho, enfim... Algo relacionado a isto.

*** 
Acredito que um simples repostório com issues de cada categoria, sendo que a pessoa somente deve comentar com seus dados de contato e disponibilidade de troca de informações;

Ou algo mais amplo para o site

**Comment by LFeh** [comment]
https://github.com/frontendbr/me-contrata :D
