### ISSUE TITLE
Plataforma de conteúdo

### ISSUE THREAD

**Issue by joaodfmota** [frontendbr/sugestoes#23]
Seguinte,

Na empresa que trabalho, prestamos manutenção a uma plataforma no qual jornalistas criam conteúdo relativo ao feminismo.

Minha sugestão seria utilizar a idéia utilizada por elas com algumas modificações no seguinte sentido:

Apoiar os colegas que criam posts auxiliando financeiramente nossa área, ou seja:

João cria um post apenas com título e descrição, ex:

Titulo: Projeto frontend para converter PSD/AI para html.
Desc: .........

Nesse sentido, quem se interessar apoia com 5, 10, 100 conforme achar melhor.

Ai a pessoa que criou o "post" começa a desenvolver e entrega para a sociedade o conteúdo, conforme a meta que ele gostaria, se não obter a meta, o recurso/money volta para a plataforma

É isso, abraços, e desculpem por mais uma issue

**Comment by LFeh** [comment]
Sugiro colocar no https://github.com/frontendbr/open-source ;)
