### ISSUE TITLE
Nova identidade para o Front-end Brasil: votação

### ISSUE THREAD

**Issue by kvnol** [frontendbr/sugestoes#24]
Com base em tudo o que foi apresentado na issue #20 (propostas lindas), esta issue ficará aberta até sexta-feira (11/08/2017) para definirmos, em votação democrática, qual será o novo logotipo para a organização Front-end Brasil.

Coloquei para votação logos que tiveram votos na issue principal, vamos votar no melhor caminho a ser seguido.  Após isso, conforme conversado com o @mtmr0x, vamos trabalhar fortemente para encaixá-lo num material de branding, com padronização de fonte, grid, posicionamento, variações etc. **Por conta disso a identidade visual final, poderá sofrer alterações.** :heart:

Matemática para contagem dos votos:

:+1: = +1 ponto;
:-1:  = -1 ponto;
:laughing: = null;
:tada: = +3 pontos;
:confused: = -2 pontos;
:heart: = +2 pontos;

Estão prontos? _(voz do Bob Esponja)_

**Comment by kvnol** [comment]
@kvnol

**Comment by kvnol** [comment]
@lazaroalvarenga

![image](https://user-images.githubusercontent.com/3299130/29029349-c7a6bc0e-7b5d-11e7-99b0-795bce6fd16a.png)

**Comment by kvnol** [comment]
@matheusmonteiro

![image](https://user-images.githubusercontent.com/3299130/29029365-d3a8fb20-7b5d-11e7-8eec-a3781a9f8ae2.png)

**Comment by kvnol** [comment]
@kvnol

![image](https://user-images.githubusercontent.com/3299130/29029378-dfaf9366-7b5d-11e7-9a90-373413ee9c41.png)

**Comment by kvnol** [comment]
@ricardogouveia3

![image](https://user-images.githubusercontent.com/3299130/29029392-ecd85db6-7b5d-11e7-8074-0d8db2995194.png)

**Comment by kvnol** [comment]
@ricardogouveia3

![image](https://user-images.githubusercontent.com/3299130/29029445-1026b722-7b5e-11e7-9538-bc71e1af1878.png)

**Comment by willianjusten** [comment]
A logo que mais me agradou foi do @matheusmonteiro, porém só acho que precisaria de um respiro um pouco melhor entre as "linhas de código" e talvez uma mudança sutil nas cores para ficar um pouquinho mais próximo de Brasil.

**Comment by mtmr0x** [comment]
@willianjusten vamos discutir isso bem, vamos votar no caminho que ficou melhor pra galera e vamos montar um material bacana. To falando com o @kvnol a respeito disso tbm aqui

**Comment by LFeh** [comment]
Sensacional @kvnol 💯

**Comment by LFeh** [comment]
A que mais me agradou foi do @matheusmonteiro também

**Comment by matheusggds** [comment]
achei a ideia do @kvnol na bandeira com [<.>] sensacional, talvez em questao de estética dê para melhorar, mas a idéia achei fantástica.
E a do @matheusmonteiro esta bem bonito, talvez com um pouco mais de sutileza como o @willianjusten fique perfeito.

**Comment by andreyazevedo** [comment]
A que o @kvnol criou ficou perfeita!

**Comment by nicolascbarbosa** [comment]
A do @matheusmonteiro ficou bem legal, uma analogia que talvez ficaria bem bacana, seria as cores das logos HTML + CSS + JS. Só uma possível sugestão mesmo.

**Comment by matheusmonteiro** [comment]
Valeu :) se rolar, eu posso fazer uma identidade mais bem acabada, esse foi feito na pressa mesmo, da pra fica bem mais bonito ;)

**Comment by jotaandrade** [comment]
![front-end](https://user-images.githubusercontent.com/9822107/29040727-81b2e4d8-7b86-11e7-93a6-ee021ef216a3.png)

**Comment by kvnol** [comment]
BROTHER, @jotaandrade. Que trampo maravilhoso! :heart:

**Comment by jotaandrade** [comment]
kkkkk vlw mano! É assim que eu visualizo!

**Comment by williamcosta** [comment]
Essa opções do @jotaandrade ta valendo na votação também?

**Comment by kvnol** [comment]
Tá valendo, @williamcosta. Pena que o @jotaandrade não mandou antes, mas está na votação.

**Comment by williamcosta** [comment]
Legal @kvnol , achei meu preferido então. HAHAHA

**Comment by kvnol** [comment]
@williamcosta já é o meu, também. HAHAHAHA

**Comment by espudaro** [comment]
O logo do @jotaandrade, é visualmente agradável e com uma fonte bem clean. Mas acho que ficou um tanto genérico, e não comunica a ideia de Front-end Brasil.
Meu preferido até agora é o  [<.>] do @kvnol.

**Comment by jotaandrade** [comment]
@espudaro concordo em termos rs. Um logo não precisa lembrar explicitamente o que ele é. Github e um exemplo disso e a Nike TB. Trampos.co por exemplo são duas montanhas.

**Comment by kvnol** [comment]
Concordo com o @jotaandrade.

**Comment by JeffersonBraga90** [comment]
Essa arte do @matheusmonteiro ficou da hora...

**Comment by lucaslimax** [comment]
[<●>] do @kvnol.

Sem dúvidas.

**Comment by espudaro** [comment]
@jotaandrade estou fazendo o papel de advogado do diabo. 😊  O logo do github é um bicho com tentáculos, Nike expressa movimento e o trampos.com visa novos horizontes. Todos tem um pq do grafismo no logo. Seu logo, como falei é bem bonito e agradável, mas acho que não representa o evento. É apenas uma opinião.

**Comment by gabrielferreiraa** [comment]
@jotaandrade mandou demais !

**Comment by jotaandrade** [comment]
Tranquilo mano rs. Tem muita logo boa aí, acho que tá bem legal a do @kvnol

**Comment by Marcelosilva10** [comment]
ótima artes, todos de excelente qualidade!

**Comment by ricardogouveia3** [comment]
Adorei esse sistema de votação que dá pra tirar ponto dos outros. Deveria ser assim nas eleições.

**Comment by robsonalvesbh** [comment]
Gostei bastante do trabalho do @jotaandrade, talvez mudaria um pouco as cores, para aproximar das outras no "estilo brasil".

**Comment by figuarnieri** [comment]
Realmente a ideia do @kvnol ficou muito boa o/ #parabens

**Comment by kvnol** [comment]
> Adorei esse sistema de votação que dá pra tirar ponto dos outros. Deveria ser assim nas eleições.

Eleições 2018, se depender de mim, os votos seriam com emojis, mas no lugar do :tada: seria o :top:

**Comment by kvnol** [comment]
A ideia do Ricardo Oliveira no [#24 (comment)](https://github.com/frontendbr/sugestoes/issues/24#issuecomment-320668373) é lindo demais, só pensaria melhor na tipografia.

**Comment by espudaro** [comment]
Outro ponto do logo [<●>] do @kvnol, e que segue uma tendência, do logo acessível, que pode ser reproduzido a partir do teclado, como recentemente a Mozz://a fez.

**Comment by kvnol** [comment]
> @espudaro: Outro ponto do logo [<●>] do @kvnol, e que segue uma tendência, do logo acessível, que pode ser reproduzido a partir do teclado, como recentemente a Mozz://a fez.

Opa! Conseguiram pegar a referência, hahaha. :heart:

**Comment by ricardogouveia3** [comment]
![](https://pbs.twimg.com/media/C6Kjd4GWcAA4IL5.jpg)

**Comment by kvnol** [comment]
> esta issue ficará aberta até sexta-feira (11/08/2017)

**Comment by kvnol** [comment]
VOTAÇÃO ENCERRADA

**Comment by kvnol** [comment]
Para deixar avisado a todos, a nova identidade do fórum foi publicada: https://github.com/frontendbr/brand

<img src="https://media.giphy.com/media/K9MPm9A3CaSkw/giphy.gif" width="300">
