### ISSUE TITLE
Sugestão para requisitos de vagas

### ISSUE THREAD

**Issue by danilovaz** [frontendbr/sugestoes#25]
Pessoal, pela primeira vez divulguei uma vaga no frontendbr/vagas e queria sugerir algo que eu fiz com a vaga da empresa que trabalho. Acredito que talvez possa ajudar tanto quem divulga quanto quem está procurando vaga.

Nos requisitos eu criei 3 tags para eu diferenciar o grau de habilidade:

**Conhecimento**, **Experiência** e **Domínio**. Dessa forma eu tanto me ajudo na hora da entrevista quanto ajudo o candidato. Onde _Conhecimento_ espera-se que o candidato pelo menos já tenha ouvido falar e saiba o que é; _Experiência_ espera-se que o candidato já tenha trabalhado com isso e _Domínio_ espera-se que ele tenha total embasamento naquilo.

Sei que é difícil controlar quem vai ou não colocar isso, mas se mudar o template da issue e na descrição da publicação das vagas, talvez ajude.

Novamente, é só uma sugestão que eu fiz no meu e acho que possa ser útil para os demais. 

Valeu :)

**Comment by LFeh** [comment]
O que acham @frontendbr/admins ?

**Comment by fdaciuk** [comment]
Acho válido!

**Comment by LFeh** [comment]
Por mim pode mandar um pull request lá @danilovaz
