### ISSUE TITLE
Uso de ferramenta pra uso das issues do GH como sistema de comments

### ISSUE THREAD

**Issue by lucianopf** [frontendbr/sugestoes#27]
Bom dia, descobri uma ferramentinha hoje que acho que seria sucesso criar uma integração com os projetos do frontendbr!

[https://utteranc.es/](https://utteranc.es/)

É animal, vejo como uma puta chance de criar uma plataforma secundária portando todos os dados e melhorando um pouquinho a interação dos usuários!

**Comment by 7Wj9ncEz** [comment]
Wow

**Comment by LFeh** [comment]
@lucianopf Só vi agora, mil desculpas haha, vou dar uma olhada

**Comment by pglapds** [comment]
Sensacional.

**Comment by felipefialho** [comment]
@lucianopf Desculpa não ter dado atenção aqui :(

Perdemos o timing

**Comment by lucianopf** [comment]
Hehehe, sem problemas mestre!! 😬 🔥
