### ISSUE TITLE
Grupos Telegram por região

### ISSUE THREAD

**Issue by kvnol** [frontendbr/sugestoes#28]
E aí, pessoal. A @larismourullo acabou de postar no Twitter:

![image](https://user-images.githubusercontent.com/3299130/37249249-be277e8e-24c2-11e8-8044-05b3f9d57875.png)

E achei interessantíssimo se tivéssemos um repositório aqui no Front-End Brasil com estes grupos do Telegram separados por região, o que acham?

PS: pensei em abrir no meu perfil, mas aqui é melhor, mais abrangente.

**Comment by LFeh** [comment]
Então @kvnol, já tivemos algumas discussões nesse sentido, estou respondendo por mim, mas creio que a maioria dos @frontendbr/admins devem concordar.

A ideia do fórum é justamente ter algo aberto, sem o mundo fechado de facebook / telegram / slack, tudo que é postado ali, fica preso. Claro, essas coisas funcionam bem para chat, off-topic e etc. Mas até hoje a gente não viu bons motivos para investir nisso.

**Comment by fdaciuk** [comment]
Concordo com o @LFeh, mas também acho válida a ideia. Talvez o que poderia ser feito é: deixar a galera interessada em abrir esses grupos por cidade, - pra quem quiser se responsabilizar em abrir - e a gente poderia ter algum lugar - talvez no README do fórum - pra deixar esses grupos listados =)

Ae a galera pode ir abrindo os grupos por região, e mandando PR no frontendbr/forum com o link para o Telegram da sua região =)

Esses lugares mais fechados podem ser interessantes pra marcar meetups, compartilhar eventos locais, e facilitar o contato pessoal da galera =)

**Comment by eduardojmatos** [comment]
Telegram = pra ideias rápidas de eventos, encontros, coisas mais rápidas de resolver.

Fórum =  pra dúvidas que precisam de mais gente envolvida e que podem ajudar mais gente, se ficar "crawleada"

❤️

**Comment by kvnol** [comment]
Concordo com o @eduardojmatos, o Telegram seria para esses papos rápidos e acho super válido.

De qualquer forma, criei o repositório no meu perfil. Qualquer coisa, só dar fork.
