### ISSUE TITLE
Sistema que filtra candidatos e vagas

### ISSUE THREAD

**Issue by danielGalvao** [frontendbr/sugestoes#29]
Conversando com o @fdaciuk reparei que temos algumas pessoas com conhecimento e experiência na área, porém se consideram junior/pleno. 
Devido a isso temos talvez uma baixa conversão de candidaturas nas vagas abertas no repositório. 
A idéia era apresentar a todas as vagas abertas filtradas pelas labels, para as pessoas, e mostrar os candidatos para os que abrem as vagas, filtrando também pelas labels.
Isso trará mais conexão entre os publicadores de vagas com os juniors/plenos e vice-versa para um possível match!
Mas ainda precisamos pensar em como fazer a cultura do medo de arriscar em uma vaga além do que se acham capaz.
Seja com feedback, seja com novas labels, seja com ajuda dos membros da comunidade.

PS: espero que tenham entendido... apenas trouxe minha sugestão...

**Comment by kvnol** [comment]
> Mas ainda precisamos pensar em como fazer a cultura do medo de arriscar em uma vaga além do que se acham capaz.

Eu me sinto muito assim, trabalho como júnior. Tem muita coisa que tem em vagas como pleno que eu manjo, mas tem muita coisa que não, por conta das necessidades de cada empresa. Aí sempre fico com o pé atrás.

**Comment by bernardodiasc** [comment]
Tem um outro lado da história que tenho percebido, são vagas pra sênior mas com salário de júnior/pleno. Digo, ao mesmo tempo que candidatos juniores se intimidam com uma label sênior, também existe um equívoco na expectativa do lado da empresa.

**Comment by kvnol** [comment]
Como o @bernardodiasc disse, também percebo que, na maioria das vezes, as empresas acham que dev é uma coisa única.

**Comment by danielGalvao** [comment]
Então, mas acho que a gente já faz uma boa filtragem para as vagas que vem mais de backend. Entendo que muitas vezes empresas fazem ofertas de vagas sinistras com salários baixos. Mas uma vez o @LFeh me fez refletir que não cabe a gente ficar policiando isso. A não ser que seja algo escravizando. Mas todos nós temos discernimento para olhar e entender que aquela vaga não é a ideal para nós. Porém agora mais do que nunca temos que respeitar, até pelo fato de abrir pra comunidade no me-contrate. Estamos expondo os usuários que querem freela, querem 100% remoto, querem PJ, querem trabalhar entende? Independente se o projeto/salário é o ideal.
Para quem está a procura, ou muito tempo sem trabalho, qualquer trabalho é trabalho.

Mas o que acham de a gente especificar mais as labels como: horários disponiveis para freela, labels técnicas (React, Angular, Bootstrap), labels de experiencia na área: (< 1 ano, 1 ano, < 3anos, < 5 anos, > 5 anos, > 10 anos)

Digo isso pois os filtros seriam muito mais relevantes utilizando a API do github

**Comment by LFeh** [comment]
@danielGalvao Labels especificando tempo de experiencia na area pode ser legal, mas não sei até que ponto faz diferença ou não para definir se é Júnior / Pleno / Senior.

Claro, tem muita vaga que quer pagar pouca, que exige muito. Mas a partir do momento que ela posta aqui, sabe que pode ser perguntada sobre as atitudes (isso acontece na verdade), é um espaço aberto e pode haver questionamentos.

**Comment by danielGalvao** [comment]
Então @LFeh na verdade não é para definir Junior / Pleno / Senior, é justamente para ajudar a dar mais noção nesse nível das pessoas, para com a comunidade. Muitas vezes as pessoas já estão a 3 anos ou mais na área, mas se sentem Junior por medo. Isso será ofuscado com as labels, os divulgadores de vagas olhando-as, saberão avaliar melhor se ele é Junior / Pleno / Senior.

Isso foi uma das coisas que me chamou atenção, as pessoas tem medo ou não se consideram por terem muitas coisas para aprender.

Quando divulguei uma vaga Senior, poucos foram que se candidataram, quando divulguei uma vaga sem distinção, as pessoas tiveram mais coragem. Eram a mesma vaga, e contratamos um Pleno quase Senior que se achava Junior quase Pleno....
