### ISSUE TITLE
Grupo Telegram?

### ISSUE THREAD

**Issue by ravenNNN** [frontendbr/sugestoes#3]
Participo de alguns grupos sobre desenvolvimento no [telegram](https://telegram.org/) e sinto que eles fluem melhor que no slack, tanto por ser uma aplicação mais leve e simples, quanto pela ótima versão web que ele oferece. Acho que seria uma boa.

**Comment by willianjusten** [comment]
Bom @ravenNNN, irei falar por mim, mas o resto da galera pode dizer depois @frontendbr/admins .

A ideia de colocar o fórum aqui é que as pessoas possam pesquisar determinados assuntos e ter sempre ali, fáceis de achar e ler. Se passar para uma plataforma de chat, são muitas pessoas falando ao mesmo tempo, nem necessariamente sobre o mesmo assunto.

Sem contar que grandes assuntos abordados no chat poderiam se perder e quem não esteve no momento, nunca mais ler...

**Comment by LFeh** [comment]
Exatamente. A ideia de procurarmos o Github é buscar escalabilidade e discussões bem elaboradas.

**Comment by Mendrone** [comment]
Concordo com o @willianjusten e o @LFeh a ideia do grupo é ser mesmo um fórum onde o conteúdo continue acessível e disponível pra todos. 

No Telegram as discussões se perderiam e sem dúvidas o conteúdo teria menos qualidade pois não seria possível a todos acompanhar onde o assunto começou e terminou.

**Comment by eduardojmatos** [comment]
@ravenNNN eu gosto de trocar ideia via chat com a galera. Mas vai por mim, participo de um que tem muuuita gente. Fica impossível acompanhar as discussões e a confusão de contexto é muito grande :cry: 

Acho que algum dia podemos pensar em ter um sim, mas mais pra descontrair, pra galera trocar ideia e etc. Discussões mais técnicas acabam indo https://github.com/frontendbr/forum

**Comment by willianjusten** [comment]
Bom, sendo assim, acho que vou fechar essa issue ok? @frontendbr/admins 
Qualquer coisa, num futuro a gente abre...
