### ISSUE TITLE
9 pessoas na org, 0 mulheres

### ISSUE THREAD

**Issue by felipebernardes** [frontendbr/sugestoes#30]
Oi pessoal, tudo bem?

Eu notei que na página da org, 100% dos organizadores são homens (https://github.com/orgs/frontendbr/people). Posso estar errado, mas parece também que são todos brancos.

Entendo que no fórum já haja diversidade nos membros, e tenhamos o código de conduta, e felizmente nunca vi ninguém sendo desrespeitados nas threads, mas **sugiro que haja uma representatividade mais diversa na nossa comunidade** :-)

Valeu

**Comment by willianjusten** [comment]
Olá Felipe, tudo bem sim 😊

Como você mesmo disse, no nosso fórum (sim, porque ele é de todos e não só dos criadores), 
temos bastante diversidade, assim como um código de conduta que protege e acolhe a todos as minorias.

Esse fórum foi criado através de algumas ideias que o @LFeh comentou no Twitter e que alguns outros acharam legal e se ofereceram para participar e ajudar. Ou seja, não existe um "dono" ou "organizador" da FrontEndBR, o que existe são amigos que tiveram uma ideia e resolveram botar em prática.

Essa ideia ficou tão legal que mais e mais pessoas começaram a participar também e cada uma delas é tão importante e representativa quanto os que iniciaram o projeto.

Mas concordamos com você que nossa organização poderia refletir melhor a diversidade do nosso fórum, dito isso fica o convite a todos que quiserem participar e ajudar.
