### ISSUE TITLE
Criar grupos para compartilhar ideias dentro do codepen.io

### ISSUE THREAD

**Issue by 7Wj9ncEz** [frontendbr/sugestoes#31]
Podíamos criar subdivisões ou mesmo divisões para compartilhar ou ter maiores projetos e inpirações no codepen.io De modo geral em todo Brasil, vejo que falta projetos visuais. A maior parte dos projetos são brancos ou nulos. Em especial, os usuários ainda não postam conteúdo relacionado ao material como por exemplo: referências e conceito inicial.

**Comment by LFeh** [comment]
Que tipo de grupo @7Wj9ncEz? No Telegram? Slack?

**Comment by 7Wj9ncEz** [comment]
Telegram e Slack ;D

**Comment by LFeh** [comment]
Então, ja rolou umas sugestões parecidas #28 #3 

A ideia é manter as discussões somente por aqui, por uma série de motivos.

Mas existem milhares de grupos no Slack e Telegram espalhados por ai, sugiro dar uma olhada neles :)
