### ISSUE TITLE
Feedback para quem se candidatou à vaga 

### ISSUE THREAD

**Issue by Roger-Melo** [frontendbr/sugestoes#32]
Será que rolaria exibir um aviso à quem postar a vaga de que é necessário, ou apenas de bom tom, que os testes enviados pelos candidatos recebam feedback? 

Será que isso ajudaria a evitar que a empresa fique muda após o candidato entregar o teste em que ele dedicou horas de esforço?

**Comment by Roger-Melo** [comment]
@LFeh exato. 

Talvez o modelo da issue possa ter uma opção em que a pessoa que postou a vaga informe um prazo estimado de retorno a quem se interessou pela vaga. Ou algo do tipo. Não sei bem o que se adequaria ao forum. Mas penso que algo desse tipo evitaria algumas situações como essas 

![feedback](https://user-images.githubusercontent.com/29297788/46039862-27a57a00-c0e5-11e8-9c82-f9ab013b7aed.png)

**Comment by LFeh** [comment]
Acredito que adicionar no template, antes da criação seja uma boa ideia. 

E ai é todos nós precisamos fiscalizar.

Quer abrir o PR @Roger-Melo?
