### ISSUE TITLE
Colocar período de vivência junto da especialidade no template do me-contrata

### ISSUE THREAD

**Issue by marquesm91** [frontendbr/sugestoes#34]
Acredito que será muito interessante para a empresa entender as especialidades fortes do candidato colocando seu período de vivência.

Por exemplo, no template do [me-contrata](https://github.com/frontendbr/me-contrata/issues/new) temos a seção especialidades da seguinte forma:

```
## Especialidades

<!--
- JavaScript
- HTML
- CSS
- PHP
-->
```

Talvez ficaria mais interessante e explício dar essa dica a todos os candidatos:

```
## Especialidades

<!-- Coloque suas especialidades na ordem da mais experiente para a menos experiente colocando o grau de vivência. -->

<!--
- JavaScript (3+ anos)
- HTML (1.5+ anos)
- CSS
- PHP
-->
```

Acredito que assim a empresa irá entender onde o candidato se destaca e aquelas especialidades que não existem um período informado significa que ele tem um conhecimento breve sobre aquilo.

**Comment by marquesm91** [comment]
Ah, estou totalmente disposto em abrir um PR, caso isso seja relevante para o projeto! Achei massa o `me-contrata`!

**Comment by felipefialho** [comment]
Gosto da ideia @marquesm91, pode seguir abrindo um PR?
