### ISSUE TITLE
Melhorar o README para as empresas do me-contrata

### ISSUE THREAD

**Issue by marquesm91** [frontendbr/sugestoes#35]
O [README](https://github.com/frontendbr/me-contrata/blob/master/README.md) está muito bem escrito e bem guiado para os candidatos interessados em se divulgar para as empresas.

Mas acho que a seção para as empresas está faltando alguns pontos para que os recrutadores se sintam confortáveis em buscar por seus candidatos.

Alguns pontos relevantes:
- Explicar com detalhes como filtrar por um cadidato
- Explicar o que é uma issue aberta e fechada
- Explicar que o que está escrito no campo de busca das issues não precisa (e nem deveria) ser apagado
- Explicar os rótulos, um a um? (talvez esse não precise, pois a linguagem usada é bem do dia a dia de recrutadores)

Acredito que possa ter mais exemplos para completar o readme, mas não consigo pensar em mais uma.

**Comment by marquesm91** [comment]
Ah, estou totalmente disposto em abrir um PR, caso isso seja relevante para o projeto! Achei foda o `me-contrata`!

**Comment by marquesm91** [comment]
Ah, estou totalmente disposto em abrir um PR, caso isso seja relevante para o projeto! Achei massa o `me-contrata`!

**Comment by felipefialho** [comment]
Novamente acho ótimo, pode adicionar essas melhorias no readme? 😄
