### ISSUE TITLE
"me contrata" para times

### ISSUE THREAD

**Issue by luizhenriquefbb** [frontendbr/sugestoes#36]
Uma seção para cadastrar times completos para trabalhos (remotos ou não), assim, se uma empresa, ou o que seja, quiser contratar um grupo que já se conhece e tem afinidade, já pode entrar em contato com o "pack".

O grupo pode dizer se conta com programador frontend, backend, fullstack e habilidades mais específicas. Enfim....

PS: Talvez saia do escopo do perfil ("frontendbr") mas fica a sugestão ....

**Comment by felipefialho** [comment]
Acho a ideia legal, mas não acho que escalaria facilmente através de issues 🤔

**Comment by munizart** [comment]
Talvez não seria a questão de postar no me contrata mesmo? invés de falar sobre um profissional em si, falar da equipe

**Comment by luizhenriquefbb** [comment]
Sim! Com certeza! Seria uma questão mais de organização... Ajudar as empresas a procurar times diretamente.

Mas sim, uma simples "tag" na seção "me contrata" resolveria =)

**Comment by felipefialho** [comment]
Acho que nessa altura não faz sentido mesmo 🤔, mas valeu pela sugestão 😄
