### ISSUE TITLE
Lugar para code review

### ISSUE THREAD

**Issue by romulosardinha** [frontendbr/sugestoes#38]
Como foi sugerido no forum. gostaria de sugerir alguma forma dos usuários pedirem um code reveiw e outros poderem ajudar.

Não sei se seria interessante o uso de um repositório apenas para isso ou se seria uma tag dentro do forum..

**Comment by felipefialho** [comment]
Só vi agora @romulosardinha, obrigado pela sugestão, vamos analisar e te retorno 😄

**Comment by felipefialho** [comment]
@romulosardinha Apesar de curtir a ideia, tenho receio do repo ficar meio abandonado. 

Deixa como algo pra depois caso essa demanda aumente no fórum, demorou? 😁
