### ISSUE TITLE
Disponibilizar formulário

### ISSUE THREAD

**Issue by LFeh** [frontendbr/sugestoes#4]
Pessoal,

Acho que podemos dar uma atenção um pouco maior ao nosso repositório de vagas para fazer ter a mesma adesão do ***fórum***.

Atualmente, apenas pessoas acostumadas ao Github conseguem criar issues. Então praticamente excluímos profissionais de RH ou de áreas afins. 

Pensei em criar um form no GoogleForms ou no TypeForm para fornecer uma forma alternativa dessas pessoas postarem as vagas.

O que acham?

@frontendbr/admins

**Comment by diogomoretti** [comment]
@LFeh cara, acho desnecessário. É mais um meio... a ideia é que os próprios devs consigam colocar vagas diretas de suas empresas ou de organizações conhecidas por ele.

O formulário não vai ter uma adesão maior. Além do mais, teríamos que passar as vagas pra cá. O que já é uma coisa que podemos fazer: passar as vagas do FB para cá =]

**Comment by LFeh** [comment]
Uhmmm, isso é verdade. Não pensei em fazer isso.

**Comment by fdaciuk** [comment]
Acho que é melhor manter só por aqui também. 

O que poderíamos fazer futuramente é algo no estilo do que será feito para o repo de [eventos](https://github.com/frontendbr/eventos/issues/3), mas com um form para facilitar adição das vagas xD

**Comment by LFeh** [comment]
Maravilha ;), vou começar a portar vagas que acho interessante para cá

**Comment by eduardojmatos** [comment]
@diogomoretti @fdaciuk @LFeh vamos ver se conseguimos gerir isso de nós mesmos colocarmos vagas ou a galera, via issues.

Mas acredito que uma hora vai ficar inviável e o formulário pode ser uma excelente opção :bowtie:
