### ISSUE TITLE
Faltou Técnologia Angular2+

### ISSUE THREAD

**Issue by marcelob-tech** [frontendbr/sugestoes#40]
boa tarde estou seguindo o frontendbr e notei que não tem a tecnologia Angular , bom seria interessante ter né, desde já obrigado

**Comment by felquis** [comment]
Eai beleza? De qualquer repositório vc está falando?

**Comment by marcelob-tech** [comment]
opa tudo blz man, então falo desse repositório 
https://github.com/frontendbr/vagas , quando na parte que tem vagas por tecnologia não tem de Angular

**Comment by felquis** [comment]
se entendi bem, vc está falando dessa sessão https://github.com/frontendbr/vagas#por-tecnologia

Caso você conheça algum repositório focado para vagas angular, compartilha aqui o link por favor.

**Comment by felquis** [comment]
mas caso você queira ver vagas no próprio repositório frontendbr/vagas, ai recomendo usar a busca https://github.com/frontendbr/vagas/issues?q=is%3Aissue+is%3Aopen+angular tem várias vagas.

**Comment by marcelob-tech** [comment]
legal obrigado :D
