### ISSUE TITLE
Landing Page - Me Contrata

### ISSUE THREAD

**Issue by rodriguesabner** [frontendbr/sugestoes#43]
Fala aí! 

Criei uma LP pra facilitar a visualização dos Devs que querem ser contratados!!
https://me-contrata.vercel.app/

Deixei o repo público também:
https://github.com/rodriguesabner/me-contrata

Parabéns pelo projeto!

**Comment by felipefialho** [comment]
Ficou bem legal @rodriguesabner, parabéns!

Se quiser pode abrir PR pra adicionar no README do [me-contrata](https://github.com/rodriguesabner/me-contrata) 😄
