### ISSUE TITLE
Mover o poste-mais para cá

### ISSUE THREAD

**Issue by LFeh** [frontendbr/sugestoes#5]
Pessoal, estou pensando em trazer o [poste-mais](https://github.com/LFeh/poste-mais) para cá. 

Acham uma boa ideia? 

Quem já deu estrela e tudo mais é notificado dessa mudança?

@frontendbr/admins

**Comment by fdaciuk** [comment]
Acredito que não muda nada.. o GitHub faz um 302 quando alguém tentar acessar o endereço antigo =)

**Comment by LFeh** [comment]
O que acha da ideia? 

Acho que faz todo sentido ;)

**Comment by fdaciuk** [comment]
Acho massa :+1: :dancer: :sparkles:

**Comment by Mendrone** [comment]
Acho massa :+1: ²

**Comment by LFeh** [comment]
Então farei isso essa semana \o

**Comment by LFeh** [comment]
Done!
