### ISSUE TITLE
Repositório para projetos open-source

### ISSUE THREAD

**Issue by LFeh** [frontendbr/sugestoes#6]
Fala pessoal, 

Estava conversando com o @eduardojmatos no MeetupCSS ontem, e percebemos uma certa demanda de pessoas que queriam ajuda para projetos open-source.

Nós já temos uma issue aberta pra isso. Mas além de ficar desorganizado, acaba não servindo tão bem ao proposito.

O que acham da criação de um repositório para esse fim?

@frontendbr/admins

**Comment by diogomoretti** [comment]
Como funcionaria?

**Comment by LFeh** [comment]
Mesmo padrão dos outros repos.

Eu tenho um projeto e queria pessoas pra me ajudar. Crio uma issue e aguardo :p

**Comment by fdaciuk** [comment]
Acho que pode ser válido. Tem uma galera que sempre pergunta: "Como eu começo a colaborar com projetos open source?"

Esse pode ser um bom caminho xD

Dá pra deixar no README do Fórum como um tópico importante também :D

**Comment by LFeh** [comment]
Vou criar o repositório. Me deem um help com o README?

**Comment by LFeh** [comment]
https://github.com/frontendbr/open-source

Precisamos de:

- [ ] Descrição decente 
- [ ] Template para as issues
- [ ] Labels

**Comment by eduardojmatos** [comment]
@LFeh boa man. Vou abrir issue lá

**Comment by LFeh** [comment]
Aproveitei e criei um cross entre todos os repositórios \o

**Comment by eduardojmatos** [comment]
@LFeh cara, ía falar exatamente isso com vc, ontem no Meetup CSS, mas esqueci heheh boa!

**Comment by eduardojmatos** [comment]
@LFeh boa, vou fechar a issue então, tudo bem?

**Comment by LFeh** [comment]
Pode fechar :D
