### ISSUE TITLE
Novas labels no repositório de vagas

### ISSUE THREAD

**Issue by eduardojmatos** [frontendbr/sugestoes#7]
Só avisando o pessoal, coloquei uma nova label lá no https://github.com/frontendbr/vagas/, **`Pendente de validação`**, pra casos de vagas que ainda precisam de revisão ou correção de informações.

cc @frontendbr/admins 

Vocês tem ideia para outras labels? Hoje temos as seguintes:

![](http://i.imgur.com/h7AZqZm.png)

**Comment by LFeh** [comment]
+1

**Comment by Mendrone** [comment]
+1

**Comment by diogomoretti** [comment]
+1

**Comment by eduardojmatos** [comment]
@LFeh @Mendrone @diogomoretti blz, vou fechar a issue! :)
