### ISSUE TITLE
Adicionar templates de abertura de issues nos repositórios

### ISSUE THREAD

**Issue by annielmenezes** [frontendbr/sugestoes#8]
Uma feature recém implementada pelo github que ajuda muito a organizar os repositórios na plataforma.

Post no blog do Github sobre a utilização [Issue and Pull Request templates](https://github.com/blog/2111-issue-and-pull-request-templates)

**Comment by LFeh** [comment]
Fala @annielmenezes, beleza?

Nós já implementamos essa funcionalidade nos repositórios de vagas, opensource e eventos (alias, consegue conferir se todos os três estão funcionando?). 

Não vejo necessidade de colocar nos outros.
