### ISSUE TITLE
Fechar issues?

### ISSUE THREAD

**Issue by LFeh** [frontendbr/sugestoes#9]
Pessoal, a @diessica me deixou com a pulga atrás da orelha [nessa issue](https://github.com/frontendbr/forum/issues/117#issuecomment-214893080).

Vocês acham que vale a pena fechar issues quando a dúvida for mais especifica, como resolver um problema e não uma discussão em sí?

@frontendbr/admins

**Comment by diogomoretti** [comment]
Penso que sim, já que a ideia é ser trackeável pelo google e pela busca do próprio GH/Repo.

**Comment by LFeh** [comment]
Então, uma dúvida pontual, igual a dessa issue, seria fechada, mas discussões abertas, não. É isso?

**Comment by diogomoretti** [comment]
👍

**Comment by LFeh** [comment]
Alguém mais?

Conseguem ajudar a fazer essa analise nas issues?

@frontendbr/admins

**Comment by eduardojmatos** [comment]
@LFeh eu acho que tem alguns casos, tipo:

1- o caso de uma pergunta ter sido respondida;
2- um problema em determinado assunto (numa ferramenta, framework, lib, etc.);
3- uma discussão sobre determinado assunto;

Os dois primeiros casos, na minha visão, podem ser fechadas de boas. Já o último, acho válido deixar aberto. Até por conta de ser exibido na lista de issues, fica mais fácil o cara entrar e bater o olho em assuntos bacanas, sem chegar via Google ou fazer busca.

Mas essa é só minha opinião. To junto com o que todo mundo decidir.

**Comment by LFeh** [comment]
Sim, tenho a mesma opinião. 

Podemos manter assim. Só vamos precisar fazer um pente fino nas issues para ver o que precisa fechar agora.

**Comment by danilovaz** [comment]
sei que ninguém perguntou, mas vou dar meu pitaco aí :joy: 

eu complementaria o comentário do @eduardojmatos que talvez fosse o caso de criar-se duas novas labels: `discussion` e `question`

`discussion`: assuntos que são opinativos e não têm uma resposta específica. ex: Como vocês estruturam o CSS? Qual o melhor pré-processador?

`question`: perguntas objetivas onde a resposta precisa ser mais certeira. ex: Como configurar o mdcss? Como desinstalo pacotes npm?

**Comment by LFeh** [comment]
Gostei da ideia @danilovaz.

O que pensam sobre isso? @frontendbr/admins

**Comment by LFeh** [comment]
Ninguém?

@frontendbr/admins

**Comment by Mendrone** [comment]
Acho que só as Labels já matam o problema. 

`discussion`
`question`
`solved`

Issues fechadas são removidas da lista principal, por isso não sei se é legal fechar.

**Comment by eduardojmatos** [comment]
@LFeh @danilovaz acho justo termos as labels.

A ideia do `solved` também faz sentido. Ao invés de fechar, adiciona a `solved`. Se alguém reabrir a discussão, removemos

**Comment by LFeh** [comment]
Vamos finalizar a ideia para botar em prática.

Então vocês acham melhor só ter uma label sobre o tipo de issue e não fechar?

**Comment by danilovaz** [comment]
Só ter a label de tipo de issue, acho que já organiza bem. Talvez fechar só as duplicadas, já mete um label de duplicada e a ref da outra issue, se alguém por acaso entrar na issue já vai saber que é duplicada

**Comment by eduardojmatos** [comment]
@LFeh @danilovaz boa. Fechar as duplicadas e adicionar `duplicated` mesmo

**Comment by LFeh** [comment]
Então vamos colocar em prática? 

Consegue criar as labels @eduardojmatos? Cria em português.

**Comment by eduardojmatos** [comment]
@LFeh então, coloquei em algumas issues, mas é muita coisa hehehe

Vou fazendo aos poucos. Quem for adicionar - @frontendbr/admins - já lembra dessas labels auxiliares.

**Comment by LFeh** [comment]
Traduzi pra ptBR e deixei em [ ] para facilitar a visualização.

Adicionei em várias issues.

Vamos fazendo aos poucos @frontendbr/admins que rapidinho a gente termina de colocar.

**Comment by eduardojmatos** [comment]
@LFeh boa! Sim, aos poucos vamos atualizando
